config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine => "jobs"

  resource :registration
  resource :session
  resource :password_reset
  resource :password
  resource :settings, only: %i[edit update]

  resources :accounts, shallow: true do
    resources :valuations
  end

  scope "accounts/new" do
    scope "bank" do
      get "", to: "accounts#new_bank", as: "new_bank"
    end

    scope "credit" do
      get "", to: "accounts#new_credit", as: "new_credit"
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"

  # newly added for dashboard
  get "net_worth_series", to: "accounts#net_worth_series"
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def update
    user_params_with_family = user_params
    # Ensure we're only updating the family associated with the current user
    if Current.family
      family_attributes = user_params_with_family[:family_attributes].merge({ id: Current.family.id })
      user_params_with_family[:family_attributes] = family_attributes
    end

    # If the family attribute for currency is changed, we need to convert all account balances to the new currency with the ConvertCurrencyJob job
    if user_params_with_family[:family_attributes][:currency] != Current.family.currency
      ConvertCurrencyJob.perform_later(Current.family)
    end

    if Current.user.update(user_params_with_family)
      redirect_to root_path, notice: "Profile updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation,
                                 family_attributes: [ :name, :id, :currency ])
  end
end

app/views/settings/edit.html.erb
<h1 class="text-3xl font-semibold font-display">Update settings</h1>

<%= form_with model: Current.user, url: settings_path, html: { class: "space-y-4" } do |form| %>
  <%= form.fields_for :family_attributes do |family_fields| %>
    <%= family_fields.text_field :name, placeholder: "Family name", value: Current.family.name, label: "Family name" %>

    <%= family_fields.select :currency, options_for_select(Currency.all.order(iso_code: :asc).map { |currency| ["#{currency.iso_code} (#{currency.name})", currency.iso_code] }, selected: Current.family.currency), { label: "Currency" } %>
  <% end %>

  <%= form.text_field :first_name, placeholder: "First name", value: Current.user.first_name, label: true %>

  <%= form.text_field :last_name, placeholder: "Last name", value: Current.user.last_name, label: true %>
  
  <%= form.email_field :email, placeholder: "Email", value: Current.user.email, label: true %>

  <%= form.password_field :password, label: true %>

  <%= form.password_field :password_confirmation, label: true %>

  <div class="fixed right-5 bottom-5">
    <button type="submit" class="flex items-center justify-center w-12 h-12 mb-2 bg-black rounded-full shrink-0 grow-0 hover:bg-gray-600">
      <%= inline_svg_tag('icn-check.svg', class: 'text-white fill-current') %>
    </button>
  </div>
<% end %>