config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine => "jobs"

  resource :registration
  resource :session
  resource :password_reset
  resource :password
  resource :settings, only: %i[edit update]

  resources :accounts, shallow: true do
    resources :valuations
  end

  scope "accounts/new" do
    scope "bank" do
      get "", to: "accounts#new_bank", as: "new_bank"
    end

    scope "credit" do
      get "", to: "accounts#new_credit", as: "new_credit"
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"

  # newly added for dashboard
  get "net_worth_series", to: "accounts#net_worth_series"
end

app/models/valuation.rb
class Valuation < ApplicationRecord
  belongs_to :account

  after_commit :sync_account_balances, on: [ :create, :update ]
  after_destroy :sync_account_balances_after_destroy

  def trend(previous)
    Trend.new(value, previous&.value)
  end

  private

    def sync_account_balances_after_destroy
      AccountBalanceSyncJob.perform_later(account_id: account_id, valuation_date: date, sync_type: "valuation", sync_action: "destroy")
    end

    def sync_account_balances
      AccountBalanceSyncJob.perform_later(account_id: account_id, valuation_date: date, sync_type: "valuation", sync_action: "update")
    end
end

app/controllers/valuations_controller.rb
class ValuationsController < ApplicationController
  before_action :authenticate_user!

  def create
    @account = Current.family.accounts.find(params[:account_id])

    # TODO: placeholder logic until we have a better abstraction for trends
    @valuation = @account.valuations.new(valuation_params.merge(currency: Current.family.currency))
    if @valuation.save
      respond_to do |format|
        format.html { redirect_to account_path(@account), notice: "Valuation created" }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  rescue ActiveRecord::RecordNotUnique
    flash.now[:error] = "Valuation already exists for this date"
    render :new, status: :unprocessable_entity
  end

  def show
    @valuation = Current.family.accounts.find(params[:account_id]).valuations.find(params[:id])
  end

  def edit
    @valuation = Valuation.find(params[:id])
  end

  def update
    @valuation = Valuation.find(params[:id])
    if @valuation.update(valuation_params)
      redirect_to account_path(@valuation.account), notice: "Valuation updated"
    else
      render :edit, status: :unprocessable_entity
    end
  rescue ActiveRecord::RecordNotUnique
    flash.now[:error] = "Valuation already exists for this date"
    render :edit, status: :unprocessable_entity
  end

  def destroy
    @valuation = Valuation.find(params[:id])
    @account = @valuation.account
    @valuation.destroy

    respond_to do |format|
      format.html { redirect_to account_path(@account), notice: "Valuation deleted" }
      format.turbo_stream
    end
  end

  def new
    @account = Current.family.accounts.find(params[:account_id])
    @valuation = @account.valuations.new
  end

  private
    def valuation_params
      params.require(:valuation).permit(:date, :value)
    end
end

app/helpers/valuations_helper.rb
module ValuationsHelper
end

app/views/valuations/_form_row.html.erb
<%# locals (f:, form_icon:, submit_button_text:)%>
<div class="h-[72px] p-4 flex items-center">
  <div class="w-16">
    <div class="w-8 h-8 rounded-full p-1.5 flex items-center justify-center bg-gray-500/5">
      <%= lucide_icon(form_icon, class: "w-4 h-4 text-gray-500") %>

       <%# This is the link that I want to be able to click and open a new form  %>
       <a data-turbo-frame="new_valuation" class="flex gap-1 font-medium items-center bg-gray-50 text-gray-900 p-2 rounded-lg" href="/accounts/90f775f6-5bae-4977-98cc-90e97b770d1d/valuations/new">
        <svg aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-5 h-5 text-gray-900"><path d="M5 12h14"></path><path d="M12 5v14"></path></svg>  
      </a>
    </div>

  </div>
  <div class="flex items-center justify-between grow">
    <%= f.date_field :date, class: "border border-alpha-black-200 bg-white rounded-lg shadow-xs min-w-[200px] px-3 py-1.5 text-gray-900 text-sm" %>
    <%= f.number_field :value, step: :any, placeholder: number_to_currency(0), in: 0.00..100000000.00, required: 'required', class: "bg-white border border-alpha-black-200 rounded-lg shadow-xs text-gray-900 text-sm px-3 py-1.5 text-right" %>
  </div>
  <div class="w-[296px] flex gap-2 justify-end items-center">
    <%= link_to "Cancel", account_path(@valuation.account), class: "text-sm text-gray-900 hover:text-gray-800 font-medium px-3 py-1.5" %>
    <%= f.submit submit_button_text, class: "bg-gray-50 rounded-lg font-medium px-3 py-1.5 cursor-pointer hover:bg-gray-100 text-sm" %>
  </div>
</div>

app/views/valuations/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Valuations#create</h1>
  <p>Find me in app/views/valuations/create.html.erb</p>
</div>

app/views/valuations/create.turbo_stream.erb
<%= turbo_stream.update Valuation.new, "" %>
<%= turbo_stream.append "notification-tray", partial: "shared/notification", locals: { type: "success", content: "Valuation created" } %>
<%= turbo_stream.replace "valuations_list", partial: "accounts/account_valuation_list", locals: { valuation_series: @account.valuation_series } %>
<%= turbo_stream.replace "sync_message", partial: "accounts/sync_message", locals: { is_syncing: true } %>

app/views/valuations/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Valuations#destroy</h1>
  <p>Find me in app/views/valuations/destroy.html.erb</p>
</div>

app/views/valuations/destroy.turbo_stream.erb
<%= turbo_stream.remove @valuation %>
<%= turbo_stream.append "notification-tray", partial: "shared/notification", locals: { type: "success", content: "Valuation deleted" } %>
<%= turbo_stream.replace "valuations_list", partial: "accounts/account_valuation_list", locals: { valuation_series: @account.valuation_series } %>
<%= turbo_stream.replace "sync_message", partial: "accounts/sync_message", locals: { is_syncing: true } %>

app/views/valuations/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Edit Valuation</h1>
  <%= turbo_frame_tag dom_id(@valuation) do %>
    <%= form_with model: @valuation, url: valuation_path(@valuation), html: { class: "" } do |f| %>
      <%= render 'form_row', f: f, form_icon: "pencil-line", submit_button_text: "Update" %>
    <% end %>
  <% end %>
</div>

app/views/valuations/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Add Valuation: <%= @account.name %></h1>
  <%= turbo_frame_tag dom_id(Valuation.new) do %>
    <%= form_with model: [@account, @valuation], url: account_valuations_path(@account), html: { class: "" } do |f| %>
      <%= render 'form_row', f: f, form_icon: "plus", submit_button_text: "Add" %>
    <% end %>
    <div class="h-px bg-alpha-black-50 ml-20 mr-4"></div>
  <% end %>
</div>

app/views/valuations/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Valuation: <%= @valuation.type %></h1>
  <p>Find me in app/views/valuations/show.html.erb</p>
</div>

app/views/valuations/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Valuations#update</h1>
  <p>Find me in app/views/valuations/update.html.erb</p>
</div>