config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine => "jobs"

  resource :registration
  resource :session
  resource :password_reset
  resource :password
  resource :settings, only: %i[edit update]

  resources :accounts, shallow: true do
    resources :valuations
  end

  scope "accounts/new" do
    scope "bank" do
      get "", to: "accounts#new_bank", as: "new_bank"
    end

    scope "credit" do
      get "", to: "accounts#new_credit", as: "new_credit"
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"

  # newly added for dashboard
  get "net_worth_series", to: "accounts#net_worth_series"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg-gray-25 h-full">
  <head>
    <title><%= content_for(:title) || "Maybe" %></title>
    <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-title" content="Maybe">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>

    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
    <%= yield :head %>
  </head>

  <body class="h-full">
    <div id="notification-tray" class="fixed top-6 right-6 space-y-1 z-50"></div>
    <%= safe_join(flash.map { |type, message| notification(message, type: type) }) %>

    <div class="flex">
      <div class="flex-col p-5 min-w-80">
        <div class="flex items-center justify-between">
          <%= link_to root_path do %>
            <%= image_tag 'logo.jpeg', alt: 'Maybe' %>
          <% end %>
          <div class="relative cursor-pointer" data-controller="dropdown">
            <div class="flex" data-action="click->dropdown#toggleMenu">
              <div class="mr-1.5 text-white w-8 h-8 bg-gray-400 rounded-full flex items-center justify-center text-lg uppercase"><%= Current.user.email.first %></div>
            </div>

            <div class="absolute z-10 hidden w-screen px-2 mt-2 -translate-x-1/2 left-1/2 max-w-min" data-dropdown-target="menu">
              <div class="w-48 px-3 text-sm font-semibold leading-6 text-gray-900 bg-white shadow-lg shrink rounded-xl ring-1 ring-gray-900/5">
                <%= link_to "Settings", edit_settings_path, class: 'block p-2 hover:text-gray-600' %>
                <%= button_to "Log Out", session_path, method: :delete, class: 'block p-2 hover:text-gray-600' %>
              </div>
            </div>

          </div>
        </div>
        <nav>
          <ul class="mt-6 space-y-1">
            <li>
              <%= sidebar_link_to t('.dashboard'), root_path, icon: 'layout-grid' %>
            </li>
            <li>
              <%= sidebar_link_to t('.accounts'), accounts_path, icon: 'layers' %>
            </li>
            <li>
              <%= sidebar_link_to t('.transactions'), "#", icon: 'credit-card' %>
            </li>
          </ul>
        </nav>
        <div class="flex flex-col mt-6">
          <div class="flex items-center justify-between">
            <%= link_to accounts_path, class: 'text-xs uppercase text-gray-500 font-bold tracking-wide' do%>
              <%= t('.accounts') %>
            <% end %>
            <%= link_to new_account_path, class: 'block hover:bg-gray-100 p-2 text-sm font-semibold text-gray-900 flex items-center rounded', title: t('.new_account'), data: { turbo_frame: "modal" } do %>
              <%= lucide_icon("plus", class: "w-5 h-5 text-gray-500") %>
            <% end %>
          </div>


          <%= link_to new_account_path, class: "flex items-center gap-4 px-2 py-3 mb-1 text-gray-500 text-sm font-medium rounded-[10px] hover:bg-gray-100", data: { turbo_frame: "modal" } do %>
            <%= lucide_icon("plus", class: "w-5 h-5") %>
            <p><%= t('.new_account') %></p>
          <% end %>

          <% Accountable.types.each do |type| %>
            <%= render 'accounts/account_list', type: Accountable.from_type(type) %>
          <% end %>
        </div>
      </div>
      <main class="flex-grow py-6 px-20">
        <%= yield %>
      </main>
    </div>
    <%= turbo_frame_tag "modal" %>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html class="h-full bg-white">
  <head>
    <title>Maybe</title>
    <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-title" content="Maybe">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body class="h-full">
    <div class="flex flex-col justify-center min-h-full px-6 py-12">

      <div class="sm:mx-auto sm:w-full sm:max-w-md">
        <%= render "shared/logo" %>

        <h2 class="mt-6 text-3xl font-semibold tracking-tight text-center font-display">
          <%= content_for?(:header_title) ? yield(:header_title).html_safe : t('.your_account') %>
        </h2>

        <% if controller_name == "sessions" %>
        <p class="mt-2 text-sm text-center text-gray-600">
          <%= t('.or') %> <%= link_to t('.sign_up'), new_registration_path, class: 'font-medium text-gray-600 hover:text-gray-400 transition' %>
        </p>
        <% elsif controller_name == "registrations" %>
        <p class="mt-2 text-sm text-center text-gray-600">
          <%= t('.or') %> <%= link_to t('.sign_in'), new_session_path, class: 'font-medium text-gray-600 hover:text-gray-400 transition' %>
        </p>
        <% end %>

      </div>

      <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-lg">
        <%= yield %>
      </div>

      <div class="p-8 mt-2 text-center">
        <p class="mt-6 text-sm text-black"><%= link_to t('.privacy_policy'), "/privacy", class: "font-medium text-gray-600 hover:text-gray-400 transition" %> &bull; <%= link_to t('.terms_of_service'), "/terms", class: "font-medium text-gray-600 hover:text-gray-400 transition" %></p>
      </div>

    </div>
  </body>
</html>